### ISSUE TITLE
Extension is Extbase or Pi1?

### ISSUE THREAD

**Issue by pouyana** [lars85/TYPO3-Extensions-lp_iframe#2]
Hi Lars,

we intend to use your extension as a replacement for our old iframe extension. After some research in the database we found out that you use the pi_flexforms to record the extension data. Is this going to be changed to own tables in the database in future release as pi1 is going to be obsolete in typo3 future releases?

Thanks in advance

**Comment by derhansen** [comment]
The extension is based on Extbase. Issue can be closed
